module config

import os

pub fn (c Config) generate_nu() string {
	// Template file: template/{shell}.nu (nushell), template/{shell}.zsh (zsh), etc.
	ext := if c.shell == 'nushell' { '.nu' } else if c.shell == 'zsh' { '.zsh' } else { '.fish' }
	template_path := 'template/' + c.shell + ext
	mut content := os.read_file(template_path) or { panic('Read template failed: $err') }

	// Replace OS icon
	content = content.replace('"󰚌 "', '"' + c.os_icon + '"')

	// Replace langs list
	langs_str := c.langs.map(fn (l string) string { return '"' + l + '"' }).join(' ')
	content = content.replace('PROMPT_LANGS: [python rust node zig go lua]', 'PROMPT_LANGS: {$langs_str}')

	// Style
	content = content.replace('TINU10K_STYLE: "lean"', 'TINU10K_STYLE: "' + c.style + '"')

	// Transient: if chosen, leave empty; if not, set to left-prompt
	if !c.transient {
		content = content.replace('TRANSIENT_PROMPT_COMMAND: ""', 'TRANSIENT_PROMPT_COMMAND: {|| left-prompt }')
	}

	// Not lean or pure
	if c.style != 'lean' && c.style != 'pure' {
		content = content.replace('PROMPT_INDICATOR_VI_INSERT: " "', 'PROMPT_INDICATOR_VI_INSERT: " "')
		content = content.replace('PROMPT_INDICATOR: " "', 'PROMPT_INDICATOR: " "')
	}

	// Two line / Sparse newlines
	dollar := '$'  // Avoid V interpolation

	if c.sparse || c.two_line {
		mut start_nl := ''
		mut end_nl := ''
		if c.sparse { start_nl = '\\n' }
		if c.two_line { end_nl = '\\n' }

		// Frame chars for two-line
		mut frame_char := ''
		mut frame_char_2 := ''
		if c.two_line && c.frame != 'none' {
			match c.frame {
				'sharp'  { frame_char = '┌─' }
				'rounded' { frame_char = '╭─' }
				'soft'   { frame_char = '╭─' }
				else     { frame_char = '' }
			}

			match c.frame {
				'sharp'  { frame_char_2 = '└─'}
				'rounded' { frame_char_2= '╰─'}
				'soft'   { frame_char_2 = '╰─'}
				else     { frame_char_2 = '' }
			}
			content = content.replace('PROMPT_INDICATOR_VI_NORMAL: " "', 'PROMPT_INDICATOR_VI_NORMAL: "󰞔 "')
		} else if c.two_line != true {
			frame_char_2 = ' '
		}

		// Process line by line
		lines := content.split('\n')
		mut new_lines := []string{}
		for line in lines {
			mut new_line := line

			// Rainbow: return $"...$prompt...$reset..."
			if line.contains('return ') && line.contains(dollar + 'prompt') {
				new_line = '    return ' + dollar + '"' + start_nl + '(' + dollar + 'prompt)(' + dollar + 'reset)' + end_nl + frame_char_2 + '"'
			}

			// Lean: final output line with both path_str and git_str
			if line.contains(dollar + 'path_str') && line.contains(dollar + 'git_str') {
				new_line = '' + dollar + '"' + start_nl + frame_char + '(' + dollar + 'path_str)(' + dollar + 'git_str)' + end_nl + frame_char_2 + '"'
			}

			new_lines << new_line
		}
		content = new_lines.join('\n')
	}

	// Classic: replace colors
	if c.style == 'classic' {
		content = content.replace('{bg: "#7e9cd8" fg: "#ffffff"}', '{bg: "#666666" fg: "#ffffff"}')
		content = content.replace('{bg: "#98bb6c" fg: "#000000"}', '{bg: "#666666" fg: "#98bb6c"}')
		content = content.replace('{bg: "#ffa066" fg: "#000000"}', '{bg: "#666666" fg: "#ffa066"}')
	}

	// Icons off: comment out icon lines
	if !c.icons {
		icon_lines := content.split('\n')
		mut icon_new_lines := []string{}
		for line in icon_lines {
			if line.contains('"python" =>') || line.contains('"rust"   =>') ||
			   line.contains('"zig"    =>') || line.contains('"node"   =>') ||
			   line.contains('"go"     =>') || line.contains('"lua"    =>') ||
			   line.contains('"v"      =>') {
				icon_new_lines << '# ' + line
			} else {
				icon_new_lines << line
			}
		}
		content = icon_new_lines.join('\n')
	}

	return '# Generated by tinu10k configure\n# Style: ' + c.style + '\n# Shell: ' + c.shell + '\n\n' + content
}
